language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    # The SDK version used to compile your project
    - android-22
    # The BuildTools version used by your project
    - build-tools-22.0.1
    - tools
    # Additional components
    # - extra-google-google_play_services
    # - extra-google-m2repository
    # - extra-android-m2repository
    # - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17
jdk: orcalejdk7
before_script: 
    - chmod +x gradlew
script: 
    - ./gradlew build check
